<article>
  <section>

    <h2>Terms of Use</h2>
    <p><em>Updated: April 5</em><em>rd</em><em>, 2023</em></p>
    <p>The services that Foundational Technologies, LLC (&ldquo;FoundTech&rdquo;) provides to you are subject to the following Terms of Use ("TOU"). FoundTech reserves the right to update and modify the TOU at any time without notice to you. The most current version of the TOU can be reviewed by clicking on the "Terms of Use" hyperlink located at the bottom of our webpages. When we make updates to the TOU, FoundTech will update the date at the top of this page. By using the website/software after a new version of the TOU has been posted, you agree to the terms of such new version. By subscribing to the FoundTech services provided by FoundTech in relation with FoundTech or FullVue and hosted on FoundTech Cloud platforms (the &ldquo;Cloud Platform&rdquo;); you are agreeing to be bound by the following TOU.</p>
    <p>The duration of this Agreement shall be specified in writing on the invoice, beginning on the due date of the invoice. It is automatically renewed for an equal Term, unless either party provides a written notice of termination minimum 30 days before the end of the Term to the other party.</p>
    <h3>Content</h3>
    <p>All content included in or made available through the Services, such as text, graphics, logos, icons, images, sounds, music, digital downloads, data compilation, software, and documents, is the exclusive property of FoundTech or its content suppliers and is protected by the various applicable trade dress, copyright, trademark, patent, and other intellectual property and unfair competition laws in the United States and internationally (collectively, "Content"). All rights not expressly granted to you in this TOU are reserved and retained by FoundTech or its licensors, suppliers, publishers, rightsholders, or other content providers.</p>
    <h3>Software</h3>
    <p>Any software that is made available to download from the Services ("Software") is the copyrighted work of FoundTech and/or its suppliers. Use of the Software is governed by the terms of the end user license agreement, if any, which accompanies or is included with the Software ("License Agreement"). An end user will be unable to install any Software that is accompanied by or includes a License Agreement, unless he or she first agrees to the License Agreement terms.</p>
    <p>The Software is made available for download solely for use by end users according to the License Agreement. Any reproduction or redistribution of the Software not in accordance with the License Agreement is expressly prohibited by law and may result in severe civil and criminal penalties. Violators will be prosecuted to the maximum extent possible.</p>
    <p>Without limiting the foregoing, copying or reproduction of the software to any other server or location for further reproduction or redistribution is expressly prohibited, unless such reproduction or redistribution is expressly permitted by the license agreement accompanying such software.</p>
    <p>The software is warranted, if at all, only according to the terms of the license agreement. Except as warranted in the license agreement, FoundTech hereby disclaims all warranties and conditions with regard to the software, including all warranties and conditions of merchantability, whether express, implied or statutory, fitness for a particular purpose, title and non-infringement. For your convenience, FoundTech may make available as part of the services or in its software products, tools, and utilities for use and/or download. FoundTech does not make any assurances with regard to the accuracy of the results or output that derives from such use of any such tools and utilities. Please respect the intellectual property rights of others when using the tools and utilities made available on the services or in FoundTech software products.</p>
    <p>Restricted Rights Legend. Any Software which is downloaded from the Services for or on behalf of the United States of America, its agencies and/or instrumentalities ("US Government"), is provided with Restricted Rights. Use, duplication, or disclosure by the US Government is subject to restrictions as set forth in subparagraph (c)(1)(ii) of the Rights in Technical Data and Computer Software clause at DFARS 252.227-7013 or subparagraphs (c)(1) and (2) of the Commercial Computer Software - Restricted Rights at 48 CFR 52.227-19, as applicable. Manufacturer is Foundational Technologies, LLC, 1020 Hartzheim Dr. Appleton, WI 54913.</p>
    <p>FoundTech commits not to disclose individual or named figures to third parties without the consent of the Customer, and to deal with all collected data in compliance with its official Privacy Policy.</p>
    <p>Upon expiration or termination of this Agreement, this license is revoked immediately and the Customer agrees to stop using the FoundTech software and the Cloud Platform.</p>
    <h3>No Unlawful or Prohibited Use</h3>
    <p>As a condition of your use of the Services, you will not use the Services for any purpose that is unlawful or prohibited by these terms, conditions, and notices. You may not use the Services in any manner that could damage, disable, overburden, or impair any FoundTech server, or the network(s) connected to any FoundTech server, or interfere with any other party's use and enjoyment of any Services. You may not attempt to gain unauthorized access to any Services, other accounts, computer systems or networks connected to any FoundTech server or to any of the Services, through hacking, password mining or any other means. You may not obtain or attempt to obtain any materials or information through any means not intentionally made available through the Services. You may not attempt to copy or change, alter, or otherwise attempt to modify the Services or these TOU.</p>
    <h3>Use of Services</h3>
    <p>The Services may contain e-mail services, bulletin board services, chat areas, news groups, forums, communities, personal web pages, calendars, photo albums, file cabinets and/or other message or communication facilities designed to enable you to communicate with others (each a "Communication Service" and collectively "Communication Services"). You agree to use the Communication Services only to post, send and receive messages and material that are proper and, when applicable, related to the particular Communication Service.</p>
    <p>FoundTech has no obligation to monitor the Communication Services. However, FoundTech reserves the right to review materials posted to the Communication Services and to remove any materials in its sole discretion. FoundTech reserves the right to terminate your access to any or all of the Communication Services at any time, without notice, for any reason whatsoever.</p>
    <p>FoundTech reserves the right at all times to disclose any information as FoundTech deems necessary to satisfy any applicable law, regulation, legal process or governmental request, or to edit, refuse to post or to remove any information or materials, in whole or in part, in FoundTech's sole discretion.</p>
    <p>Always use caution when giving out any personally identifiable information about yourself or your children in any Communication Services. FoundTech does not control or endorse the content, messages or information found in any Communication Services and, therefore, FoundTech specifically disclaims any liability with regard to the Communication Services and any actions resulting from your participation in any Communication Services. Managers and hosts are not authorized FoundTech spokespersons, and their views do not necessarily reflect those of FoundTech.</p>
    <p>Materials uploaded to the Communication Services may be subject to posted limitations on usage, reproduction and/or dissemination; you are responsible for adhering to such limitations if you download the materials.</p>
    <h3>Services</h3>
    <p>For the duration of this Agreement, FoundTech commits to making all reasonable efforts to remedy any Bug of the Software submitted by the Customer through the appropriate channel and to start handling such Customer submissions within a reasonable amount of time. As soon as the Bug is fixed an appropriate remedy will be communicated to the Customer. Both parties acknowledge that as specified in the license of the Software and in the Limitation of Liability section of this Agreement, FoundTech cannot be held liable for Bugs in the Software.</p>
    <p>FoundTech commits to apply the security remedies for any security Bug discovered in a version of the Software hosted on the Cloud Platform, on all systems under its control, as soon as the remedy is available, without requiring any manual action of the Customer.</p>
    <p>For the duration of this Agreement, the Customer may open an unlimited number of support tickets free of charge, exclusively for questions regarding Bugs or guidance with respect to the use of the standard features of the Software.</p>
    <p>Other assistance requests, such as questions related to development or customizations may be covered through the purchase of a separate service agreement. In case it&rsquo;s not clear if a request is covered by this Agreement, the decision is at the discretion of FoundTech</p>
    <p>Tickets can be submitted via the web form, phone number or email.</p>
    <h3>Privacy, and Customer Data</h3>
    <p>Review the Privacy Statement disclosures relating to the collection and use of your personal data.</p>
    <h3>Conditions of Services</h3>
    <p>The Customer agrees to pay FoundTech any applicable charges for the Services of the present Agreement, in accordance with the payment conditions specified at the signature of this contract; immediately notify FoundTech when their actual number of Users exceeds the number specified at the conclusion of the Agreement, and in this event, pay the applicable additional fee as described in section Standard charges.</p>
    <p>When the Customer chooses to use the Cloud Platform, the Customer further agrees to take all reasonable measures to keep their user accounts secure, including by choosing a strong password and not sharing it with anyone else.</p>
    <p>Except where notified otherwise in writing, each party grants the other a non-transferable, non-exclusive, royalty free, worldwide license to reproduce and display the other party&rsquo;s name, logos and trademarks, solely for the purpose of referring to the other party as a customer or supplier, on websites, press releases and other marketing materials.</p>
    <h3>Data Protection</h3>
    <p>The parties acknowledge that the Customer&rsquo;s database may contain Personal Data, for which the Customer is the Controller. This data will be processed by FoundTech when the Customer instructs so, by using any of the Services that require a database, or if the Customer transfers their database or a part of their database to FoundTech for any reason pertaining to this Agreement.</p>
    <p>This processing will be performed in conformance with Data Protection Legislation. In particular, FoundTech commits to:</p>
    <ol type="a">
      <li>Only process the Personal Data when and as instructed by the Customer, and for the purpose of performing one of the Services under this Agreement, unless required by law to do so, in which case FoundTech will provide prior notice to the Customer, unless the law forbids it</li>
      <li>Ensure that all persons within FoundTech authorized to process the Personal Data have committed themselves to confidentiality of Personal Data</li>
      <li>Implement and maintain appropriate technical and organizational measures to protect the Personal Data against unauthorized or unlawful processing and against accidental loss, destruction, damage, theft, alteration or disclosure</li>
      <li>Forward promptly to the Customer any Data Protection request that was submitted to FoundTech with regard to the Customer&rsquo;s database</li>
      <li>Notify the Customer promptly upon becoming aware of and confirming any accidental, unauthorized, or unlawful processing of, disclosure of, or access to the Personal Data</li>
      <li>Notify the Customer if the processing instructions infringe applicable Data Protection Legislation, in the opinion of FoundTech</li>
      <li>Make available to the Customer all information necessary to demonstrate compliance with the Data Protection Legislation, allow for and contribute reasonably to audits, including inspections, conducted or mandated by the Customer</li>
      <li>Permanently delete all copies of the Customer&rsquo;s database in possession of FoundTech, or return such data, at the Customer&rsquo;s choice, upon termination of this Agreement, subject to the delays specified in FoundTech&rsquo;s Privacy Policy</li>
    </ol>
    <p>In the event that either Party fails to fulfill any of its obligations arising herein, and if such breach has not been remedied within 30 calendar days from the written notice of such breach, this Agreement may be terminated immediately by the non-breaching Party.</p>
    <p>Further, FoundTech may terminate the Agreement immediately in the event the Customer fails to pay the applicable fees for the Services within 14 calendar days following the due date specified on the corresponding invoice, and after minimum 3 reminders.</p>
    <h3>Disclaimer of Warranties</h3>
    <p>EXCEPT AS WARRANTED IN A SEPARATE AGREEMENT, FOUNDTECH AND ITS RESPECTIVE SUPPLIERS PROVIDE THE SERVICES (INCLUDING THE CONTENT AND APIS) &ldquo;AS IS,&rdquo; &ldquo;WITH ALL FAULTS&rdquo; AND &ldquo;AS AVAILABLE.&rdquo; YOU BEAR THE RISK OF USING IT. WE PROVIDE NO WARRANTIES, GUARANTEES OR CONDITIONS, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. YOU MAY HAVE ADDITIONAL RIGHTS UNDER YOUR LOCAL LAWS WHICH THIS AGREEMENT CANNOT CHANGE. THESE DISCLAIMERS WILL APPLY TO THE FULLEST EXTENT PERMITTED UNDER APPLICABLE LAW, INCLUDING APPLICATION TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.</p>
    <ol>
      <li>Third party content and materials. FOUNDTECH DOES NOT CONTROL, REVIEW, REVISE, ENDORSE, OR ACCEPT RESPONSIBILITY FOR ANY THIRD PARTY CONTENT, INFORMATION, MESSAGES, MATERIALS, PROJECTS ACCESSIBLE FROM OR LINKED THROUGH THE SERVICES, AND, EXCEPT AS WARRANTED IN A SEPARATE AGREEMENT, FOUNDTECH MAKES NO REPRESENTATIONS OR WARRANTIES WHATSOEVER ABOUT AND SHALL NOT BE RESPONSIBLE FOR ANY OF THE FOREGOING. ANY DEALINGS YOU MAY HAVE WITH SUCH THIRD PARTIES ARE AT YOUR OWN RISK.</li>
    </ol>
    <h3>Limitation of Liability</h3>
    <p>Except as expressly provided herein, neither party makes any warranty of any kind, whether express, implied, statutory or otherwise, and each party specifically disclaims all implied warranties, including any implied warranty of merchantability, fitness for a particular purpose or non-infringement, to the maximum extent permitted by applicable law.</p>
    <p>In no event shall FoundTech and/or its respective suppliers be liable for any special, indirect or consequential damages, or any damages whatsoever resulting from loss of use, data, or profits, whether in an action of contract, negligence or other tortious action, arising out of or in connection with the use or performance of software, documents, provision of or failure to provide services, or information available from the services.</p>
    <p>Neither party shall be liable to the other party for the delay in any performance or failure to render any performance under this Agreement when such failure or delay finds its cause in a case of force majeure, such as governmental regulations, fire, strike, war, flood, accident, epidemic, embargo, appropriation of plant or product in whole or in part by any government or public authority, or any other cause or causes, whether of like or different nature, beyond the reasonable control of such party as long as such cause or causes exist.</p>
    <h3>Member Account, Password, and Security</h3>
    <p>If any of the Services requires you to open an account, you must complete the registration process by providing us with current, complete, and accurate information as prompted by the applicable registration form. You also will choose a password and a username. You are entirely responsible for maintaining the confidentiality of your password and account. Furthermore, you are entirely responsible for any and all activities that occur under your account. You agree to notify FoundTech immediately of any unauthorized use of your account or any other breach of security. FoundTech will not be liable for any loss that you may incur as a result of someone else using your password or account, either with or without your knowledge. However, you could be held liable for losses incurred by FoundTech or another party due to someone else using your account or password. You may not use anyone else's account at any time, without the permission of the account holder.</p>
    <h3>Links to Third-party Sites</h3>
    <p>The links in this area will let you leave FoundTech&rsquo;s site. The linked sites are not under the control of FoundTech and FoundTech is not responsible for the contents of any linked site or any link contained in a linked site, or any changes or updates to such sites. FoundTech is not responsible for webcasting, or any other form of transmission received from any linked site. FoundTech is providing these links to you only as a convenience, and the inclusion of any link does not imply endorsement by FoundTech of the site.</p>
    <h3>Definitions</h3>
    <p>&ldquo;Customer Data&rdquo; means any Content or other data, including all text, sound, video, or image files, or software, that are provided to us by, or on behalf of, you through your use of the Developer Services for use by you or your authorized users. Customer Data does not include Submissions or any other Content or data that you submit to the Documentation Portal or otherwise provide via the Developer Services for public access.</p>
    <p>&ldquo;User&rdquo; means any user account indicated as active in the Software, with access to creation and/or edition mode. Deactivated user accounts and accounts used by external people (or systems) who only have limited access to the Software through the portal facilities (known as &ldquo;portal Users&rdquo;) are not counted as Users.</p>
    <p>&ldquo;App&rdquo; means a specialized group of features available for installation in the Software.</p>
    <p>&ldquo;Bug&rdquo; Is considered a Bug any failure of the Software or of a Covered Extra Module that results in a complete stop, error traceback or security breach, and is not directly caused by a defective installation or configuration. Non-compliance with specifications or requirements will be considered as Bugs at the discretion of FoundTech.</p>
    <p>&ldquo;Subscription Plan&rdquo; defines a set of Apps, features and hosting solutions covered by this Agreement, and is defined in writing at the conclusion of this Agreement.</p>
    <h3>Standard Charges and Fees</h3>
    <p>The standard charges for the FoundTech subscription and the Services are based on the number of Users and the Subscription Plan used by the Customer, and specified in writing at the conclusion of the Agreement.</p>
    <p>When during the Term, the Customer has more Users or uses features that require another Subscription Plan than specified at the time of conclusion of this Agreement, the Customer agrees to pay an extra fee equivalent to the applicable list price (at the time of the deviation from the specified number of Users or Subscription Plan) for the additional Users or the required Subscription Plan, for the remainder of the Term.</p>
    <p>Upon renewal, if the charges applied during the previous Term are lower than the most current applicable list price, these charges are subject to change.</p>
    <p>All fees and charges are exclusive of all applicable federal, provincial, state, local or other governmental taxes, fees or charges (collectively, &ldquo;Taxes&rdquo;). The Customer is responsible for paying all Taxes associated with purchases made by the Customer under this Agreement, except when FoundTech is legally obliged to pay or collect Taxes for which the Customer is responsible.</p>
  </section>
</article>
<style>
  article {
    margin: 0 auto;
    max-width: 90%;
  }
  p {
    font-size: 18px;
    margin: .8em 0;
  }
  h3 {
    font-size: 22px;
    margin: 1em 0;
  }
  @media (min-width: 1000px) {
    article {
      max-width: 940px;
    }
  }
</style>